### ISSUE TITLE
Little CSS Error

### ISSUE THREAD

**Issue by PapeCoding** [BlueTeck/kanboard_plugin_bigboard#10]
I noticed some weird CSS in the assets.
```CSS
.btn.BB {
	width: calc( 100% - 25px );
}
```
should be exchanged with
```CSS
.btn.BB {
	width: 100%;
	box-sizing: border-box;
}
```

I don't want to do a pull request for two lines. Maybe you can add it in a future release :)
